import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import vm from "node:vm";

const source = readFileSync(new URL("../assets/bible-app.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../assets/bible-app.css", import.meta.url), "utf8");

function extractFunction(name) {
  const start = source.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `Missing ${name} in bible-app.js`);
  const bodyStart = source.indexOf(") {", start) + 2;
  let depth = 0;
  for (let index = bodyStart; index < source.length; index += 1) {
    if (source[index] === "{") depth += 1;
    if (source[index] === "}") depth -= 1;
    if (depth === 0) return source.slice(start, index + 1);
  }
  throw new Error(`Could not extract ${name}`);
}

const functionNames = [
  "focusBrandVersionHoldEnabled",
  "handleBrandVerseOfDayClick",
  "beginFocusBrandVersionHold",
  "updateFocusBrandVersionHold",
  "endFocusBrandVersionHold",
  "cancelFocusBrandVersionHold",
  "suppressFocusBrandContextMenu",
  "openFocusBrandVersionMenu",
];

assert.match(source, /focus-brand-version-menu/);
assert.match(source, /state\.mode === "parallel" \? parallelVersionOptions : primaryVersionHeaderOptions/);
assert.match(source, /brandVerseOfDay\?\.addEventListener\("pointerdown", beginFocusBrandVersionHold\)/);
assert.match(styles, /\.app-shell \.focus-brand-version-menu \{[\s\S]*?display:\s*grid;/);
assert.match(styles, /\.brand\.version-hold-pending::before \{[\s\S]*?animation:\s*mobileSettingsHoldProgress 350ms linear forwards;/);

let scheduledHold = null;
let now = 1000;
let renders = 0;
let verseOfDayOpens = 0;
let portrait = true;
let compact = true;
let shortLandscape = false;
const context = {
  state: {
    focusMode: true,
    mode: "reader",
    focusReferenceOpen: true,
    focusSearchResultsOpen: true,
    focusToolsOpen: true,
    focusWorkspacePanel: "History",
    settingsOpen: true,
    accountOpen: true,
    footerVersionMenuOpen: true,
    headerVersionMenuOpen: false,
  },
  window: {
    matchMedia: (query) => ({ matches: query === "(orientation: portrait)" && portrait }),
  },
  Date: { now: () => now },
  setTimeout(callback, delay) {
    scheduledHold = { callback, delay };
    return 7;
  },
  clearTimeout() {
    scheduledHold = null;
  },
  isCompactScreen: () => compact,
  isShortLandscapeScreen: () => shortLandscape,
  resetFocusToolSurfaces() {
    context.state.focusToolsOpen = false;
    context.state.focusWorkspacePanel = "";
  },
  renderPreservingReaderScroll() {
    renders += 1;
  },
  openVerseOfDay() {
    verseOfDayOpens += 1;
  },
};
vm.createContext(context);
vm.runInContext(`
  let focusBrandVersionHoldTimer = 0;
  let focusBrandVersionHoldGesture = null;
  let suppressFocusBrandClickUntil = 0;
  const mobileControlsHoldMs = 350;
  const mobileControlsHoldMoveTolerancePx = 12;
  ${functionNames.map(extractFunction).join("\n")}
  globalThis.handleClick = handleBrandVerseOfDayClick;
  globalThis.beginHold = beginFocusBrandVersionHold;
  globalThis.moveHold = updateFocusBrandVersionHold;
  globalThis.endHold = endFocusBrandVersionHold;
  globalThis.suppressContextMenu = suppressFocusBrandContextMenu;
`, context);

const pendingClasses = new Set();
const brandButton = {
  classList: {
    add: (name) => pendingClasses.add(name),
    remove: (name) => pendingClasses.delete(name),
  },
};
const pointerEvent = (overrides = {}) => ({
  currentTarget: brandButton,
  isPrimary: true,
  pointerType: "touch",
  pointerId: 3,
  clientX: 24,
  clientY: 22,
  ...overrides,
});

context.beginHold(pointerEvent());
assert.equal(scheduledHold.delay, 350, "The version menu uses the established mobile hold timing");
assert.equal(pendingClasses.has("version-hold-pending"), true);
scheduledHold.callback();
assert.equal(context.state.headerVersionMenuOpen, true);
assert.equal(context.state.footerVersionMenuOpen, false);
assert.equal(context.state.settingsOpen, false);
assert.equal(context.state.accountOpen, false);
assert.equal(context.state.focusReferenceOpen, false);
assert.equal(context.state.focusSearchResultsOpen, false);
assert.equal(context.state.focusToolsOpen, false);
assert.equal(context.state.focusWorkspacePanel, "");
assert.equal(renders, 1);

let prevented = 0;
const clickEvent = {
  preventDefault: () => { prevented += 1; },
  stopPropagation: () => {},
};
context.handleClick(clickEvent);
assert.equal(prevented, 1, "The click generated by a completed hold is suppressed");
assert.equal(verseOfDayOpens, 0, "A completed hold does not also open Verse of the Day");
now = 2000;
context.handleClick(clickEvent);
assert.equal(verseOfDayOpens, 1, "An ordinary tap keeps the Verse of the Day action");

context.beginHold(pointerEvent());
context.moveHold(pointerEvent({ clientX: 37 }));
assert.equal(scheduledHold, null, "Moving beyond the gesture tolerance cancels the hold");
assert.equal(pendingClasses.has("version-hold-pending"), false);

let contextMenuPrevented = false;
context.suppressContextMenu({ preventDefault: () => { contextMenuPrevented = true; } });
assert.equal(contextMenuPrevented, true);

for (const focusMode of [false, true]) {
  for (const mode of ["reader", "parallel"]) {
    for (const landscape of [false, true]) {
      context.state.focusMode = focusMode;
      context.state.mode = mode;
      portrait = !landscape;
      compact = !landscape;
      shortLandscape = landscape;
      context.beginHold(pointerEvent());
      assert.equal(scheduledHold?.delay, 350, `${mode} supports holding with Focus ${focusMode} and landscape ${landscape}`);
      scheduledHold.callback();
      assert.equal(context.state.headerVersionMenuOpen, true);
      context.endHold(pointerEvent());
    }
  }
}
compact = false;
shortLandscape = false;
for (const mode of ["reader", "parallel"]) {
  for (const pointerType of ["mouse", "touch", "pen"]) {
    context.state.mode = mode;
    context.beginHold(pointerEvent({ pointerType, button: 0 }));
    assert.equal(scheduledHold?.delay, 350, `${mode} supports desktop ${pointerType} holds`);
    scheduledHold.callback();
    assert.equal(context.state.headerVersionMenuOpen, true);
    context.endHold(pointerEvent());
  }
}
context.beginHold(pointerEvent({ pointerType: "mouse", button: 2 }));
assert.equal(scheduledHold, null, "Right-click does not start a hold");
context.beginHold(pointerEvent({ pointerType: "mouse", button: 0 }));
context.endHold(pointerEvent());
assert.equal(scheduledHold, null, "Releasing the mouse before the hold completes cancels it");
compact = true;
for (const mode of ["big", "trivia"]) {
  context.state.mode = mode;
  context.beginHold(pointerEvent());
  assert.equal(scheduledHold, null, `${mode} does not enable the version hold`);
}

console.log("Focus brand version hold tests passed");
