import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync(new URL("../assets/bible-app.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../assets/bible-app.css", import.meta.url), "utf8");

function extractFunction(name) {
  const start = source.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `Missing ${name} in bible-app.js`);
  const bodyStart = source.indexOf(") {", start) + 2;
  assert.ok(bodyStart > 1, `Could not find ${name} body in bible-app.js`);
  let depth = 0;
  for (let index = bodyStart; index < source.length; index += 1) {
    if (source[index] === "{") depth += 1;
    if (source[index] === "}") depth -= 1;
    if (depth === 0) return source.slice(start, index + 1);
  }
  throw new Error(`Could not extract ${name} from bible-app.js`);
}

assert.match(source, /gamesDrawerOpen: ""/);
assert.match(source, /state\.mode === "trivia" \? "trivia-shell" : ""/);
assert.match(source, /\["trivia", "Games", icons\.games\]/);
assert.match(source, /data-trivia-mode="trivia"[\s\S]*?icons\.trivia/);
assert.match(source, /id="gameSocialToggle"[\s\S]*?aria-controls="gamesSocialDrawer"/);
assert.match(source, /id="gameOptionsToggle"[\s\S]*?aria-controls="gamesOptionsDrawer"/);
assert.match(source, /id="gameControlsToggle"[\s\S]*?aria-controls="gamesControlsDrawer"/);
assert.match(source, /id="gameControlsToggle"[\s\S]{0,450}?\$\{icons\.controls\}/);
assert.match(source, /controls: '<svg[\s\S]*?<circle cx="15" cy="12" r="2"\/>/);
assert.match(source, /returnBack: '<svg[\s\S]*?M4 12h9a7 7 0 0 1 7 7/);
assert.match(source, /id="gameHintsToggle"[\s\S]*?aria-controls="gamesHintsDrawer"/);
assert.match(source, /class="trivia-start-dock"[\s\S]*?id="startTriviaGame"/);
assert.match(source, /class="games-drawer games-options-drawer"[\s\S]*?role="dialog"/);
assert.match(source, /class="games-drawer games-social-drawer"[^>]*?role="dialog" aria-modal="true"/);
assert.match(source, /class="games-drawer games-controls-drawer"[\s\S]*?role="dialog"/);
assert.match(source, /class="games-drawer games-hints-drawer"[\s\S]*?role="dialog"/);
assert.match(source, /gamesUseDrawers \? 'role="dialog" aria-modal="true"' : 'role="region"'/);
assert.equal(source.match(/\$\{gameChallengeSetupCard\(\)\}/g)?.length, 1);
assert.match(extractFunction("setGamesDrawer"), /renderPreservingReaderScroll\(\)/);
assert.match(extractFunction("setGamesDrawer"), /focus\(\{ preventScroll: true \}\)/);
assert.match(extractFunction("trapGamesDrawerFocus"), /event\.key === "Escape"/);
assert.match(extractFunction("trapGamesDrawerFocus"), /event\.key !== "Tab"/);
assert.match(extractFunction("centerActiveTriviaMode"), /tabs\.scrollLeft/);
assert.doesNotMatch(extractFunction("centerActiveTriviaMode"), /isGamesResponsiveScreen/);
assert.match(extractFunction("mountMobileGameControls"), /gamesActiveControlsBody/);
assert.match(extractFunction("mountMobileGameControls"), /gamesAnswerDialogBody/);
assert.match(extractFunction("mountMobileGameControls"), /gamesHintDrawerBody/);
assert.match(extractFunction("mountMobileGameControls"), /hintDestination\.append\(hints\)/);
assert.match(extractFunction("mountMobileGameControls"), /book-sprint-sound-toggle/);
assert.match(extractFunction("mountMobileGameControls"), /destination\.append\(bookSprintSound\)/);
assert.match(extractFunction("mountMobileGameControls"), /#checkBookSprint, #checkVerseOrder/);
assert.match(extractFunction("mountMobileGameControls"), /checkDock\.append\(orderingCheck\)/);
assert.match(extractFunction("mountMobileGameControls"), /game\.after\(checkDock\)/);
assert.match(extractFunction("mountMobileGameControls"), /querySelectorAll\(":scope > \.trivia-actions"\)/);
assert.match(extractFunction("mountMobileGameControls"), /\.trivia-feedback:not\(\.book-sprint-retry\)/);
assert.match(extractFunction("openGamesHints"), /hintMenuOpen = true/);
assert.match(extractFunction("updateTriviaModeScrollControls"), /canScrollNext/);
assert.match(extractFunction("scrollTriviaModes"), /tabs\.scrollBy/);
assert.match(source, /data-trivia-mode-scroll="1"[\s\S]*?aria-label="Show more games"/);
assert.match(source, /class="reference-rush-stage"/);
assert.match(source, /class="trivia-results-summary"/);
assert.match(source, /data-fragment-count="\$\{puzzle\.segments\.length\}" data-order-bank-drop/);
assert.match(source, /class="book-sprint-sound-icon"[\s\S]*?icons\.timer/);
assert.match(source, /class="book-sprint-sound-copy"[\s\S]*?Audible countdown/);
assert.match(extractFunction("startTriviaGame"), /state\.gamesDrawerOpen = ""/);
assert.match(extractFunction("switchMode"), /nextMode !== "trivia"[\s\S]*?state\.gamesDrawerOpen = ""/);
assert.match(extractFunction("triviaExitControl"), /games-menu-control[\s\S]*?icons\.returnBack[\s\S]*?Games menu/);
assert.match(extractFunction("crosswordGameView"), /games-menu-control crossword-menu-control[\s\S]*?icons\.returnBack[\s\S]*?Games menu/);

assert.match(styles, /\.games-drawer-shell,[\s\S]*?\.games-drawer-scroll \{[\s\S]*?display: contents;/);
assert.match(styles, /\.games-menu-control \{[\s\S]*?display: inline-flex;[\s\S]*?gap: 7px;/);
assert.match(styles, /\.games-menu-control svg \{[\s\S]*?width: 18px;[\s\S]*?height: 18px;/);
assert.match(styles, /#gameSocialToggle,\s*#gameControlsToggle \{[\s\S]*?display: inline-flex;/);
assert.match(styles, /\.games-drawer-shell:is\(\[data-games-drawer="social"\], \[data-games-drawer="controls"\]\) \{[\s\S]*?display: none;/);
assert.match(styles, /\.games-drawer-shell:is\(\[data-games-drawer="social"\], \[data-games-drawer="controls"\]\)\.open \{[\s\S]*?position: fixed;[\s\S]*?display: block;/);
assert.match(styles, /\.games-drawer-shell:is\(\[data-games-drawer="social"\], \[data-games-drawer="controls"\]\) \.games-drawer \{[\s\S]*?position: fixed;[\s\S]*?animation: gamesDrawerInRight/);
assert.match(styles, /\.trivia-reader\.is-setup \{[\s\S]*?overflow: hidden;/);
assert.match(source, /state\.focusMode && !state\.settingsOpen[\s\S]*?mobileFloatingSettings/);
assert.doesNotMatch(styles, /\.app-shell\.trivia-shell \.mobile-floating-settings\s*\{[^}]*display:\s*(?:inline-)?flex;/);
assert.match(styles, /\.app-shell\.trivia-shell \.footer-collapse-toggle \{[\s\S]*?left: 0;[\s\S]*?right: 0;/);
assert.match(styles, /\.trivia-setup \{[\s\S]*?grid-template-rows: auto minmax\(0, 1fr\) auto;/);
assert.match(styles, /\.trivia-mode-tabs \{[\s\S]*?grid-auto-flow: column;[\s\S]*?overflow-x: auto;/);
assert.match(styles, /\/\* Games keeps options inline on desktop[\s\S]*?\.trivia-mode-picker \{[\s\S]*?display: block;[\s\S]*?width: min\(900px, 100%\);/);
assert.match(styles, /\.trivia-mode-scroll-next \{[\s\S]*?right: 0;[\s\S]*?border-radius: 12px 0 0 12px;/);
assert.match(styles, /\.trivia-mode-scroll-previous \{[\s\S]*?left: 0;[\s\S]*?border-radius: 0 12px 12px 0;/);
assert.match(styles, /\.trivia-mode-scroll \{[\s\S]*?width: 34px;[\s\S]*?height: 44px;[\s\S]*?opacity: 0\.56;/);
assert.match(styles, /\.trivia-mode-scroll:hover,[\s\S]*?opacity: 1;/);
assert.match(styles, /\.trivia-mode-picker\.can-scroll-next::after \{[\s\S]*?right: 0;/);
assert.match(styles, /\.games-answer-overlay:not\(\[hidden\]\) \{[\s\S]*?place-items: center;/);
assert.match(styles, /\.games-answer-dialog-body #nextTriviaQuestion \{[\s\S]*?grid-row: 1;/);
assert.match(styles, /\.trivia-result-ring:not\(\.book-sprint-time-ring\) \{[\s\S]*?height: 128px;[\s\S]*?aspect-ratio: 1;/);
assert.match(styles, /\.trivia-start-dock \{[\s\S]*?display: grid;/);
assert.match(styles, /\.games-drawer-shell\.open \{[\s\S]*?position: fixed;/);
assert.match(styles, /@media \(max-width: 840px\) and \(orientation: portrait\) \{[\s\S]*?\.games-options-drawer,\s*\.games-hints-drawer \{[\s\S]*?top: auto;[\s\S]*?left: 0;[\s\S]*?animation-name: gamesDrawerInBottom;/);
assert.doesNotMatch(styles, /\.games-options-drawer,\s*\.games-controls-drawer,\s*\.games-hints-drawer/);
assert.match(styles, /\.games-drawer-shell:is\(\[data-games-drawer="social"\], \[data-games-drawer="controls"\]\) \.games-drawer \{[\s\S]*?right: 0;[\s\S]*?animation: gamesDrawerInRight/);
assert.match(styles, /@media \(orientation: landscape\) and \(max-width: 1366px\) and \(max-height: 720px\) \{[\s\S]*?\.trivia-start-dock \{[\s\S]*?grid-column: 2;/);
assert.match(styles, /@media \(orientation: landscape\) and \(max-width: 1366px\) and \(max-height: 720px\) \{[\s\S]*?\.app-shell\.trivia-shell \{[\s\S]*?height: 100dvh;[\s\S]*?overflow: hidden;/);
assert.match(styles, /@media \(orientation: landscape\) and \(max-width: 1366px\) and \(max-height: 720px\) \{[\s\S]*?\.app-shell > \.main-grid\.trivia-grid \{[\s\S]*?height: auto;[\s\S]*?align-self: stretch;[\s\S]*?overflow: hidden;/);
assert.match(styles, /@media \(orientation: landscape\) and \(max-width: 1366px\) and \(max-height: 720px\) \{[\s\S]*?\.trivia-grid \.trivia-reader\.is-playing \{[\s\S]*?height: auto;[\s\S]*?overflow: hidden;/);
assert.match(styles, /@media \(orientation: landscape\) and \(max-width: 1366px\) and \(max-height: 720px\) \{[\s\S]*?\.games-answer-dialog \{[\s\S]*?width: min\(900px, 100%\);[\s\S]*?max-height: calc\(100dvh - 24px\);/);
assert.match(styles, /@media \(orientation: landscape\) and \(max-width: 1366px\) and \(max-height: 720px\) \{[\s\S]*?\.games-answer-dialog-body \{[\s\S]*?grid-template-columns: minmax\(0, 1fr\) minmax\(210px, 0\.38fr\);/);
assert.match(styles, /\.games-answer-dialog-body #nextTriviaQuestion \{[\s\S]*?grid-column: 1;[\s\S]*?grid-row: 1;/);
assert.match(styles, /\.reference-rush-stage \{[\s\S]*?grid-template-columns: minmax\(0, 1\.25fr\) minmax\(260px, 0\.75fr\);/);
assert.match(styles, /\.reference-rush-timer-meter \{[\s\S]*?grid-column: 2;[\s\S]*?grid-row: 1;/);
assert.match(styles, /\.trivia-reader\.is-playing \.trivia-results \{[\s\S]*?align-content: start;/);
assert.match(styles, /\.book-sprint-game \.book-sprint-meter \{[\s\S]*?grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
assert.match(styles, /\.games-active-controls \.book-sprint-sound-toggle \{[\s\S]*?grid-template-columns: 40px minmax\(0, 1fr\) auto;/);
assert.match(styles, /\.games-active-controls \.book-sprint-sound-toggle \{[\s\S]*?width: min\(260px, 100%\);/);
assert.match(styles, /\.games-active-controls \.book-sprint-sound-icon \{[\s\S]*?background: var\(--teal\);/);
assert.match(styles, /\.games-active-controls \.book-sprint-sound-toggle\[aria-pressed="true"\] \.book-sprint-sound-state/);
assert.match(styles, /\.ordering-check-dock \{[\s\S]*?flex: 0 0 auto;[\s\S]*?width: 100%;/);
assert.match(styles, /\.ordering-check-dock :is\(#checkBookSprint, #checkVerseOrder\) \{[\s\S]*?min-height: 48px;/);
assert.match(styles, /\.verse-order-game \{[\s\S]*?align-content: start;[\s\S]*?gap: 10px;/);
assert.match(styles, /\.verse-order-game h2 \{[\s\S]*?font-size: clamp\(21px, 5vw, 28px\);[\s\S]*?text-align: center;/);
assert.match(styles, /\.verse-order-game \.book-sprint-instructions \{[\s\S]*?font-size: clamp\(12px, 3\.2vw, 14px\);/);
assert.match(styles, /\.verse-order-game \.verse-fragment-bank:is\(\[data-fragment-count="5"\],[\s\S]*?grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
assert.match(styles, /\.games-controls-drawer \{[\s\S]*?width: min\(300px, 76vw\);/);
assert.match(styles, /\.trivia-reader\.is-playing \.trivia-results-summary \{[\s\S]*?display: grid;/);
assert.match(styles, /--games-overlay-tint: rgba\(0, 0, 0, 0\.58\);/);
assert.match(styles, /@media \(prefers-reduced-motion: reduce\) \{[\s\S]*?animation-duration: 1ms !important;/);

console.log("Games mobile layout tests passed");
